In [1]:
import numpy as np

In [2]:
import numpy as np
print(np.__version__)

2.1.1


In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#0 d array
arr = np.array(42)
print(arr)

42


In [5]:
#1 d array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
#2d array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#3d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
#check number of dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
#slicing
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [11]:
#slicing
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [12]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [13]:
#2d array slicing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [14]:
#3d slicing 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


6


In [15]:
#negative indexing 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [16]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [19]:
#negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [22]:
#slicing 2 arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [23]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [24]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [25]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4])

[15 20 25]


- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [26]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [27]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [61]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [29]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [50]:
#converting data type into existing array
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('f')
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float32


In [31]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [32]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [33]:
#copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42 #index number
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [34]:
#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [36]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [37]:
original_array = np.array([1, 2, 3])
x = original_array.copy()
x[0] = 5
print(original_array)

[1 2 3]


In [38]:
#shaping array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [39]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [40]:
#array reshaping
#1D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
#2D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [43]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
#Flattening array means converting a multidimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
